[package]
name = "gameboy-rs"
version = "0.1.0"
authors = ["Ruben <chickenzrage@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
sdl2 = "0.34.5"
ggez = "0.5.1"